datasets:
  measures_bedmachine_antarctica:
    display_name: BedMachine Antarctica
    path: /Users/lawrence.bird/Documents/data/datapool/measures_bedmachine_antarctica
    description: High-resolution bed topography and ice thickness data for Antarctica.
    tags:
      - antarctica
      - bed topography
      - ice thickness
      - surface elevation
      - bed uncertainty
      - ice mask
    extension: nc
  
  bedmap:
    display_name: Bedmap
    path: /Users/lawrence.bird/Documents/data/datapool/bedmap
    description: Gridded, geospatial, and point datasets of Antarctic ice thickness, surface elevation, and bed elevation.
    tags:
      - antarctica
      - bed topography
      - ice thickness
      - surface elevation
    subdatasets:
      v1:
        geospatial:
          subpath: geospatial_data
          extension: gpkg
          no_data_value: -9999
        points:
          subpath: point_data
          extension: csv
          skip_lines: 18
          no_data_value: -9999
        gridded:
          subpath: gridded_data
          extension: tif
      v2:
        geospatial:
          subpath: geospatial_data
          extension: gpkg
          no_data_value: -9999
          ignore_dirs:
            - shapeLines
        points:
          subpath: point_data
          extension: csv
          skip_lines: 18
          no_data_value: -9999
        gridded:
          subpath: gridded_data
          extension: tif
          ignore_dirs:
            - resources
      v3:
        geospatial:
          subpath: geospatial_data
          extension: gpkg
          no_data_value: -9999
          ignore_dirs:
            - shapeLines
        points:
          subpath: point_data
          extension: csv
          skip_lines: 18
          no_data_value: -9999
        gridded:
          subpath: gridded_data
          extension: nc
          ignore_dirs:
            - bm3_streamlines_pt